=== mmr/b1n.org/projects.xsd
<?xml version='1.0' encoding='ISO-8859-1'?>
<!--
/**
 * @author Marcio Ribeiro <mribeiro (a) gmail com>
 * @created 2005-10-15
 * @version $Id: projects.xsd,v 1.3 2006/02/13 05:05:39 mmr Exp $
 */
-->
<xsd:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
    xmlns:mmr='http://b1n.org'
    xmlns='http://b1n.org'
    targetNamespace='http://b1n.org'
    elementFormDefault='qualified'>

    <!-- Types -->
    <xsd:simpleType name='string'>
        <xsd:restriction base='xsd:string'>
            <xsd:whiteSpace value='collapse'/>
            <xsd:minLength value='1'/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- project -->
    <xsd:element name='project'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name='name' type='mmr:string'/>
                <xsd:element name='desc' type='mmr:string'/>
                <xsd:element name='status' type='xsd:integer' minOccurs='0'/>
                <xsd:element name='path' type='mmr:string' minOccurs='0'/>
                <xsd:element name='technologies'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='technology' type='mmr:string'
                                minOccurs='1' maxOccurs='unbounded'>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- workProjects -->
    <xsd:element name='workProjects'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:attribute name='title' type='mmr:string' use='required'/>
                <xsd:attribute name='subtitle' type='mmr:string'/>
                <xsd:element ref='project' maxOccurs='unbounded'/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- hobbyProjects -->
    <xsd:element name='hobbyProjects'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref='project' maxOccurs='unbounded'/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Cv -->
    <xsd:element name='projects'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref='workProjects'/>
                <xsd:element ref='hobbyProjects'/>
            </xsd:sequence>
            <xsd:attribute name='author' type='mmr:string' use='required'/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== mmr/b1n.org/projects.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<?xml-stylesheet type='text/xsl' href='projects.xsl'?>
<!--
/**
 * @author Marcio Ribeiro <mribeiro (a) gmail com>
 * @created 2005-10-15
 * @version $Id: projects.xml,v 1.13 2006/07/07 12:39:14 mmr Exp $
 */
-->
<projects
    author='Marcio Ribeiro'
    xmlns='http://b1n.org'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://b1n.org projects.xsd'>

    <workProjects
        title='Projetos Profissionais'
        subtitle='"Sucesso só vem antes de Trabalho no dicionário." (Vince Lombardi)'>
        <project>
            <name>ASA</name>
            <desc>
            ASA significa Aberium Security Advisor, não é bem um projeto, é mais um serviço prestado.
            Semanalmente, eu escrevia resumos sucintos sobre as últimas falhas encontradas em aplicações e sistemas diversos.
            As descrições das falhas eram retiradas de conceituados sites e listas sobre segurança.</desc>
            <path>work/asa</path>
        </project>

        <project>
            <name>Airgate</name>
            <desc>
            Ferramenta para controle de roteamento de redes wireless utilizando firewall ipf (IP Filter em FreeBSD) e VPN (Virtual Private Network) utilizando PPTP (Point to Point Tunelling Protocol) para clientes Windows.
            </desc>
            <path>work/airgate</path>
            <technologies>
                <technology>PHP</technology>
                <technology>PostgreSQL</technology>
                <technology>IPF em FreeBSD</technology>
            </technologies>
        </project>

        <project>
            <name>Apyon</name>
            <desc>
            A Apyon/GSDNet, já possuia um sistema de controle (escrito em ASP/JScript) de clientes funcionando, porém, esse sistema possuía muito código em JavaScript escrito de forma bem pouco portável, não funcionando em muitos navegadores (leia, diferente de Internet Explorer). Boa parte do código JavaScript foi reescrito, colocando detecções de browsers (IE 4/5/6, Netscape 4.7+, Mozilla, etc) e 'emulando' os efeitos desejados na medida do possível. Compatibilizando também os CSS's (Cascading Style Sheets) entre os navegadores.
            </desc>
            <technologies>
                <technology>ASP (JScript)</technology>
                <technology>DHTML (JavaScript e CSS)</technology>
                <technology>Microsoft SQL Server</technology>
            </technologies>
        </project>

        <project>
            <name>Busca PDF</name>
            <desc>Sistema de pesquisa em conteudo de arquivos PDF indexados baseado no htdig.</desc>
            <path>work/htdig</path>
            <technologies>
                <technology>C</technology>
                <technology>Htdig</technology>
                <technology>XPDF</technology>
            </technologies>
        </project>

        <project>
            <name>CP Finasa</name>
            <desc>Piloto para sistema de controle de cargas em cartão de crédito para a Certegy.</desc>
            <path>work/cpf</path>
            <technologies>
                <technology>Java</technology>
                <technology>Struts</technology>
                <technology>EJB</technology>
                <technology>Oracle</technology>
                <technology>JBoss</technology>
            </technologies>
        </project>

        <project>
            <name>KM</name>
            <desc>Sistema de gestao de conhecimento (Knowledge Management) para Probank.</desc>
            <path>work/km</path>
            <technologies>
                <technology>Java</technology>
                <technology>JSF</technology>
                <technology>Hibernate</technology>
                <technology>PostgreSQL</technology>
                <technology>JBoss</technology>
            </technologies>
        </project>

        <project>
            <name>DocuShare</name>
            <desc>Treinamento sobre o DocuShare, software de controle de conteudo e documentos eletronicos (GED / ECM - Enterprise Content Management) da Xerox.</desc>
            <path>work/docushare</path>
            <technologies>
                <technology>Tomcat</technology>
                <technology>Java</technology>
                <technology>DocuShare</technology>
            </technologies>
        </project>

        <project>
            <name>Documentor</name>
            <desc>Sistema que simula um cliente HTTP para automatizar tarefas de de geracao de documentacao em formato PDF atraves do Wiki (TWiki).</desc>
            <path>work/documentor</path>
            <technologies>
                <technology>Java</technology>
                <technology>HttpClient</technology>
            </technologies>
        </project>

        <project>
            <name>E-Nós2</name>
            <desc>
            Desenvolvimento e manutenção do site de relacionamento E-NÓS2, constando de content management (Controle de Conteúdo), fóruns, enquetes e afins.
            </desc>
            <path>work/enos2</path>
            <technologies>
                <technology>PHP</technology>
                <technology>Perl</technology>
                <technology>MySQL</technology>
            </technologies>
        </project>

        <project>
            <name>EuToFacinho</name>
            <desc>
            O EuToFacinho (formado pela parceria Enos2+Trip+TPM) é um site de relacionamento onde as pessoas (que 'estão facinho') se cadastram (enviando suas fotos), esperando que os visitantes os correspondam via email, dessa forma aumentando seu número de 'cantadas'.
            </desc>
            <path>work/eutofacinho</path>
            <technologies>
                <technology>PHP</technology>
                <technology>MySQL</technology>
            </technologies>
        </project>

        <project>
            <name>ExtracaoPDF</name>
            <desc>
            Sistema que cria uma versão PDF de cada uma das páginas da Folha de S.Paulo, edições São Paulo e Nacional.
            </desc>
            <path>work/extracaopdf</path>
            <technologies>
                <technology>Perl</technology>
                <technology>Distiller</technology>
            </technologies>
        </project>

        <project>
            <name>FGV</name>
            <desc>
            Sistema de gerenciamento desenvolvido para a Empresa Júnior da Faculdade/Fundação Getúlio Vargas.
            Consta de controle de permissões, envio/recepção de tasks entre usuários, módulo de Consultoria, Eventos, TimeSheet, Etiquetagem, Backup, Avisos Automáticos (Crontab), entre outros.
            </desc>
            <path>work/fgv</path>
            <technologies>
                <technology>PHP</technology>
                <technology>Perl</technology>
                <technology>PostgreSQL</technology>
            </technologies>
        </project>

        <project>
            <name>Flywatch</name>
            <desc>Sistema de controle de vôos executivos.</desc>
            <path>work/flywatch</path>
            <technologies>
                <technology>PHP</technology>
                <technology>FPDF</technology>
                <technology>Perl</technology>
                <technology>PostgreSQL</technology>
            </technologies>
        </project>

        <project>
            <name>FolhaWiki</name>
            <desc>
            Implantação de sistema de base de conhecimento (knowledge base) para a tecnologia da Folha de S.Paulo. 
            </desc>
            <path>work/extracaopdf</path>
            <technologies>
                <technology>PHP</technology>
                <technology>MySQL</technology>
                <technology>MediaWiki</technology>
            </technologies>
        </project>

        <project>
            <name>Importer</name>
            <desc>
            Importador de documentos em formato SGML/XML (Dublin Core) para banco de dados SQL Server.
            </desc>
            <path>work/importer</path>
            <technologies>
                <technology>Perl</technology>
                <technology>Microsoft SQL Server</technology>
            </technologies>
        </project>

        <project>
            <name>GPM</name>
            <desc>GPM (Gerencia de Produtos e Materiais) é um sistema de controle de processos. Com diversos módulos, como de Produção e Logística que cuidam das etapas para fabricação real de produtos e toda parte de logística física de recebimento e envio de materiais e produtos.</desc>
            <path>work/gpm</path>
            <technologies>
                <technology>Java</technology>
                <technology>Groovy</technology>
                <technology>Struts</technology>
                <technology>Hibernate</technology>
                <technology>Velocity</technology>
                <technology>Oracle iAS</technology>
            </technologies>
        </project>

        <project>
            <name>GVI</name>
            <desc>Montagem e documentação de servidores de paginas e nomes com .</desc>
            <path>work/gvi</path>
            <technologies>
                <technology>LaTeX</technology>
                <technology>Perl</technology>
                <technology>FreeBSD</technology>
                <technology>BIND</technology>
                <technology>Apache</technology>
            </technologies>
        </project>

        <project>
            <name>iBest</name>
            <desc>Piloto de CMS para o iBest.</desc>
            <path>work/ibest</path>
            <technologies>
                <technology>PHP</technology>
                <technology>PostgreSQL</technology>
            </technologies>
        </project>

        <project>
            <name>LDAP</name>
            <desc>Unificacao de autenticacao de usuarios de diversos servicos - Email, servidor de arquivos, proxy, rede - em LDAP.</desc>
            <path>work/htdig</path>
